Resources:
    User:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: cpf
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: cpfIndex
                  KeySchema:
                      - AttributeName: cpf
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: cpf
                  KeyType: HASH
            TableName: ${self:app}-user-${self:custom.stage}
    Parking:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: spot
                  AttributeType: S
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: spotIndex
                  KeySchema:
                      - AttributeName: spot
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: spot
                  KeyType: HASH
            TableName: ${self:app}-parking-${self:custom.stage}
