Resources:
    User:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: uuid
                  AttributeType: S
                - AttributeName: cpf
                  AttributeType: S
                - AttributeName: timestamp
                  AttributeType: N
            BillingMode: PAY_PER_REQUEST
            GlobalSecondaryIndexes:
                - IndexName: cpfIndex
                  KeySchema:
                      - AttributeName: cpf
                        KeyType: HASH
                      - AttributeName: timestamp
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
            KeySchema:
                - AttributeName: uuid
                  KeyType: HASH
                - AttributeName: timestamp
                  KeyType: RANGE
            TableName: ${self:app}-user-${self:custom.stage}
